### ISSUE TITLE
value_replacer stopped working

### ISSUE THREAD

**Issue by SummerZheng** [robertzk/syberiaMungebits#50]
If I run your examples:
https://github.com/robertzk/syberiaMungebits/blob/master/R/value_replacer.r#L11-L12
it gives the following error
![image](https://cloud.githubusercontent.com/assets/8315577/9695374/9a0569a0-5326-11e5-8756-a0c9ac549901.png)

**Comment by robertzk** [comment]
I think its an R 3.2 issue. I'll look into it shortly.

On Friday, September 4, 2015, SummerZheng <notifications@github.com> wrote:

> If I run your examples:
>
> https://github.com/robertzk/syberiaMungebits/blob/master/R/value_replacer.r#L11-L12
> it gives the following error
> [image: image]
> <https://cloud.githubusercontent.com/assets/8315577/9695374/9a0569a0-5326-11e5-8756-a0c9ac549901.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertzk/syberiaMungebits/issues/50>.
>


-- 
-Robert Krzyzanowski

**Comment by FeiYeYe** [comment]
R 3.2.2 fails too

**Comment by eddieyue** [comment]
any update?

**Comment by robertzk** [comment]
The example is wrong. Sorry about that.

```r
> df <- data.frame(x = c("A", "B", "C", "D", NA))
> value_replacer(df, TRUE, list(list(c("A", "B", "D"), 1), list(NA, 0)))
> head(df)
  x
1 1
2 1
3 C
4 1
5 0
```
